name: Move assigned tasks to Fred in Notion
on:
  issues:
    types:
      - assigned
  workflow_dispatch:

jobs:
  add_to_notion:
    #if: ${{ github.event.assigned.assignee == 'fharper' }}

    runs-on: ubuntu-latest
    steps:
    - name: Debug
      uses: hmarr/debug-action@v2
      
    - name: Webhook
      uses: distributhor/workflow-webhook@v3
      with:
        #webhook_url: ${{ secrets.NOTION_WEBHOOK_URL }}
        webhook_url: "https://hooks.zapier.com/hooks/catch/13285796/3oeps9o/"
        data: '{ "issue": "${github.event.assigned.issue.url}}", "title": "${{github.event.assigned.issue.title }}", "content": "${{github.event.assigned.issue.body}}" }'
