---
name: Markdown Syntax Validation
on: [push, workflow_dispatch]

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@master

      - name: Temporarily disable docs branch protections
        uses: fharper/branch-protection-bot@master
        with:
          access_token: ${{ secrets.DOCS_PERMISSIONS_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}

      - name: Enable back docs branch protection
        uses: fharper/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure the protection is always turned back on no matetr if previous step fail
        with:
          access_token: ${{ secrets.DOCS_PERMISSIONS_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
